### ISSUE TITLE
Specify NVIDIA runtime version info compatible with the trace artifact 

### ISSUE THREAD

**Issue by supersergiy** [ZettaAI/zetta_utils#133]

**Comment by dodamih** [comment]
Looks more into it, and it doesn't actually seem that runtime version affects torchscript - the device does get pinned for some operations though. If we do something like multi-gpu training, ops that happened on device 2 for instance get compiled to be on device 2 for some operations (e.g. `tensor > threshold`).

**Comment by dodamih** [comment]
I think the bigger issue is that torchscript is dependent on the torch version. They claim that they will try to maintain backward compatibility between versions but don't guarantee forward compatibility - this might end up being a more prevalent issue since docker files will usually have lower pytorch versions than what we train on.

**Comment by dodamih** [comment]
TorchScript just outputs statically typed python code, and torch is responsible for compiling it to the architecture that it's being run on - so if torch installs fine (it will barf if you try to install torch<1.10 on my box for instance with the architecture issue - see these gencodes: https://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/) there shouldn't be an issue with compatibility as far as the runtime is concerned I think. I think the torch version is more relevant for compatibility, so I'll add that in instead.
